[package]
name = "q_ambientcg_extract"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
cfg-if = "1.0.0"
image = "0.25.2"
indicatif = { version = "0.17.8", features = ["rayon"] }
rayon = "1.10.0"
smallvec = "1.13.2"
thiserror = "1.0.63"
zip = "2.1.6"

